//
//  WhitePptPage.h
//  WhiteSDK
//
//  Created by leavesster on 2018/8/15.
//

#import <UIKit/UIkit.h>
#import "WhiteObject.h"

NS_ASSUME_NONNULL_BEGIN

/** Configuration for the parameters of a PPT slide to be inserted into the scene.
 
 You can pass in a `PptPage` object when initializing a `Scene` instance to present the image or dynamic PPT slide on the whiteboard scene.
 
 You can insert the following formats of an image or dynamic PPT slide on the whiteboard scene:
  
  - Static images in PNG, JPG/JPEG, and WEBP formats, or PNG, JPG/JPEG, and WEBP images which are converted from PPT, PPTX, DOC, DOCX, and PDF files.
  - Dynamic PPT slides which are converted from PPTX files using the [Agora file conversion service](https://docs.agora.io/cn/whiteboard/file_conversion_overview?platform=RESTful).
 */
@interface WhitePptPage : WhiteObject

/** Initializes a `WhitePptPage` object to be inserted on a whiteboard scene.

 **Note:**

 - You can insert only one image or dynamic PPT slide on a whiteboard scene.
 - The image or dynamic PPT slide displayed on the whiteboard scene takes the origin of the world coordinate system as the center and cannot be changed, which means you cannot change the position of the image or dynamic PPT slide inside the whiteboard.

 @param src The address of the image or dynamic PPT slide. The supported formats are as follows:

 - For image: The URL address, which can be generated by yourself or by using the Agora file conversion service. For example, `"https://docs-test-xxx.oss-cn-hangzhou.aliyuncs.com/staticConvert/2fdxxxxx67e/1.jpeg"`.
 - For dynamic PPT slide: The URI address, which is generated by using the Agora file conversion service. For example, `"pptx://cover.herewhite.com/dynamicConvert/6a212c90fa5311ea8b9c074232aaccd4/1.slide"`.
 @param size The size (px) of the image or dynamic PPT slide.

 @return An Initialized `WhitePptPage` object.
 */
- (instancetype)initWithSrc:(NSString *)src size:(CGSize)size;

/** Initializes a `WhitePptPage` object to be inserted on a whiteboard scene.

 **Note:**

 - You can insert only one image or dynamic PPT slide on a whiteboard scene.
 - The image or dynamic PPT slide displayed on the whiteboard scene takes the origin of the world coordinate system as the center and cannot be changed, which means you cannot change the position of the image or dynamic PPT slide inside the whiteboard.

 @param src The address of the image or dynamic PPT slide. The supported formats are as follows:

 - For image: The URL address, which can be generated by yourself or by using the Agora file conversion service. For example, `"https://docs-test-xxx.oss-cn-hangzhou.aliyuncs.com/staticConvert/2fdxxxxx67e/1.jpeg"`.
 - For dynamic PPT slide: The URI address, which is generated by using the Agora file conversion service. For example, `"pptx://cover.herewhite.com/dynamicConvert/6a212c90fa5311ea8b9c074232aaccd4/1.slide"`.
 @param url The URL address of the preview image for the image or dynamic PPT slide. You can get the URL address of the dynamic PPT preview in the `preview` field in [the query result of the file conversion task](https://docs.agora.io/en/whiteboard/whiteboard_file_conversion?platform=RESTful#query-file-conversion-progress-get). For example, "https://docs-test-xxx.oss-cn-hangzhou.aliyuncs.com/dynamicConvert/2fdxxxxx67e/preview/1.png".

 @param size The size (px) of the image or dynamic PPT slide.

 @return An Initialized `WhitePptPage` object.
 */
- (instancetype)initWithSrc:(NSString *)src preview:(NSString *)url size:(CGSize)size;

/**
 The address of the image or dynamic PPT slide. The supported formats are as follows:

 - For image: The URL address, which can be generated by yourself or by using the Agora file conversion service. For example, `"https://docs-test-xxx.oss-cn-hangzhou.aliyuncs.com/staticConvert/2fdxxxxx67e/1.jpeg"`.
 - For dynamic PPT slide: The URI address, which is generated by using the Agora file conversion service. For example, `"pptx://cover.herewhite.com/dynamicConvert/6a212c90fa5311ea8b9c074232aaccd4/1.slide"`.
 */
@property (nonatomic, copy) NSString *src;
/**
 The width (px) of the image or dynamic PPT slide.
 */
@property (nonatomic, assign) CGFloat width;
/**
 The height (px) of the image or dynamic PPT slide.
 */
@property (nonatomic, assign) CGFloat height;

/**
 The URL address of the preview image for the image or dynamic PPT slide. 
 
 You can get the URL address of the dynamic PPT preview in the `preview` field in [the query result of the file conversion task](https://docs.agora.io/en/whiteboard/whiteboard_file_conversion?platform=RESTful#query-file-conversion-progress-get). For example, "https://docs-test-xxx.oss-cn-hangzhou.aliyuncs.com/dynamicConvert/2fdxxxxx67e/preview/1.png".
 */
@property (nonatomic, copy, readonly) NSString *previewURL;

@end

NS_ASSUME_NONNULL_END
